services:
  postgres:
    image: postgres:16.9
    container_name: postgres
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_DB=unipe-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root

  api-unipe:
    container_name: api-unipe
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - POSTGRES_DATABASE=unipe-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
